-- 1. Create Role & Warehouse
USE ROLE ACCOUNTADMIN;
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;

-- 2. Create Database
CREATE DATABASE IF NOT EXISTS GREYSTAR_PROPTECH_DB;

-- 3. Create Medallion Schemas
CREATE SCHEMA IF NOT EXISTS GREYSTAR_PROPTECH_DB.BRONZE_RAW;
CREATE SCHEMA IF NOT EXISTS GREYSTAR_PROPTECH_DB.SILVER_STG;
CREATE SCHEMA IF NOT EXISTS GREYSTAR_PROPTECH_DB.GOLD_MARTS;
